kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vsphere-fast
  annotations:
provisioner: kubernetes.io/vsphere-volume
parameters:
    datastore: ds-vcenter
    diskformat: zeroedthick
    fstype: ext4
reclaimPolicy: Delete
